### ISSUE TITLE
Simplified implementation with react-hooks

### ISSUE THREAD

**Issue by amytych** [IniZio/Magic-Grid-React#4]
Hi there, I experimented a bit and came up with a thin wrapper around magic-grid using react hooks.
What do you think about this idea? Would you be open to consider switching to it? Or do you prefer your current approach?

I realise this is a big departure from your current approach and it requires pretty recent version of react, so I'd completely understand if you're not open to it. In that case I'd go ahead and publish it as a separate lib `react-magic-grid`. I'd mention your lib in README as well, so people can choose one that suits them best. Just wanted to check with you first.

The whole implementation is like this:

```jsx
import React, { useEffect, useRef } from "react"
import PropTypes from "prop-types"
import MagicGrid from "magic-grid"

// thin react wrapper around magic-grid
// accepts all magic-grid config options via props
const MagicGridWrapper = ({ children, ...props }) => {
  const container = useRef(null)
  let grid = null

  useEffect(() => {
    let timeout
    // magic-grid handles resizing via its own `listen` method
    // unfortunately event listener it creates is not being cleaned up
    // that's why we don't use it and have our own instead
    // see: https://github.com/e-oj/Magic-Grid/issues/24
    const resize = () => {
      if (!timeout)
        timeout = setTimeout(() => {
          grid && grid.positionItems()
          timeout = null
        }, 200)
    }

    if (!grid) {
      grid = new MagicGrid({ container: container.current, ...props })
      window.addEventListener("resize", resize)
    }

    grid.positionItems()

    return () => {
      window.removeEventListener("resize", resize)
    }
  })

  return <div ref={container}>{children}</div>
}

MagicGridWrapper.propTypes = {
  children: PropTypes.arrayOf(PropTypes.node),
}

export default MagicGridWrapper
```

**Comment by IniZio** [comment]
Thanks @amytych for the suggestion! I prefer not to make the change though because hook does not make as much difference in terms of functionality and performance.

I will mention in this repo's README.md as well once you make the hook implementation :)

**Comment by amytych** [comment]
Cool, I'll close it then, thanks for the response!

**Comment by IniZio** [comment]
@all-contributors please add @amytych for ideas
